### ISSUE TITLE
Big_chungus.png isn't sus enough

### ISSUE THREAD

**Issue by wensenfriendandextra** [Vyxal/Sandbox#17]
We need to make it more sus

ඞ

**Comment by Makonede** [comment]
![amogus](https://user-images.githubusercontent.com/61922615/151227809-6d9bc333-46fd-41cb-b0e1-d932455cc592.png)

**Comment by wensenfriendandextra** [comment]
bump

**Comment by wensenfriendandextra** [comment]
#44 merged
